default_node = "127.0.0.1:9000"

[[my_keys]]
public = "wallet_b.pub.pem"
private = "wallet_b.priv.cbor"

[[contacts]]
name = "WalletA"
key = "wallet_a.pub.pem"

[fee_config]
fee_type = "Percent"
value = 0.1
